{{ if .Values.ciliumNetworkPolicy.enabled }}
apiVersion: "cilium.io/v2"
kind: CiliumNetworkPolicy
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ .Values.name }}
  labels:
    {{- include "labels.common" . | nindent 4 }}
spec:
  endpointSelector:
    matchLabels:
      {{- include "labels.selector" . | nindent 6 }}
  egress:
    - toEntities:
      - kube-apiserver
      - world
    - toEndpoints:
      - matchLabels:
          app.kubernetes.io/name: net-exporter
          io.kubernetes.pod.namespace: kube-system
      toPorts:
      - ports:
        - port: {{ .Values.port | quote }}
          protocol: TCP
  ingress:
    - fromEndpoints:
      - matchLabels:
          app.kubernetes.io/name: alloy
          io.kubernetes.pod.namespace: kube-system
      - matchLabels:
          app.kubernetes.io/name: net-exporter
          io.kubernetes.pod.namespace: kube-system
      toPorts:
      - ports:
        - port: {{ .Values.port | quote }}
          protocol: TCP
{{ end }}
