{{- if .Values.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: net-exporter
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "labels.common" . | nindent 4 }}
spec:
  endpoints:
    - interval: {{ .Values.serviceMonitor.interval }}
      path: /metrics
      port: metrics
      scrapeTimeout: {{ .Values.serviceMonitor.scrapeTimeout }}
      relabelings:
        - action: replace
          sourceLabels:
          - __meta_kubernetes_pod_label_app
          targetLabel: app
        - action: replace
          sourceLabels:
          - __meta_kubernetes_pod_node_name
          targetLabel: node
  selector:
    matchLabels:
      {{- include "labels.selector" . | nindent 6 }}
{{- end }}
