apiVersion: v1
kind: Service
metadata:
  name: net-exporter
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "labels.common" . | nindent 4 }}
spec:
  ports:
    - name: metrics
      port: {{ .Values.port }}
      targetPort: metrics
  selector:
    {{- include "labels.selector" . | nindent 4 }}
