version: 2.1
orbs:
  architect: giantswarm/architect@8.3.0

workflows:
  build:
    jobs:
    - architect/go-build:
        name: go-build-net-exporter
        context: architect
        binary: net-exporter
        architectures: "linux/amd64,linux/arm64"
        filters:
            # Trigger the job also on git tag.
          tags:
            only: /^v.*/

    - architect/push-to-registries:
        context: architect
        name: push-to-registries
        image: giantswarm/net-exporter
        multiarch: true
        requires:
        - go-build-net-exporter
        filters:
          tags:
            only: /^v.*/

          branches:
            ignore:
            - main
            - master
    - architect/push-to-app-catalog:
        executor: app-build-suite
        context: architect
        name: push-net-exporter-to-control-plane-app-catalog
        app_catalog: control-plane-catalog
        app_catalog_test: control-plane-test-catalog
        chart: net-exporter
        requires:
        - push-to-registries
        filters:
          tags:
            only: /^v.*/

          branches:
            ignore:
            - main
            - master
    - architect/push-to-app-catalog:
        executor: app-build-suite
        context: architect
        name: push-net-exporter-to-default-app-catalog
        app_catalog: default-catalog
        app_catalog_test: default-test-catalog
        chart: net-exporter
        requires:
        - push-to-registries
        filters:
          tags:
            only: /^v.*/

          branches:
            ignore:
            - main
            - master
